progize_welcome_homepage:
    pattern:  /
    defaults: { _controller: proGizeWelcomeBundle:Welcome:init }

progize_featured_projects:
    pattern: /featured
    defaults : {_controller: proGizeWelcomeBundle:Featured:init }

progize_login:
    prefix:  /login
    resource: "@proGizeUserManagementBundle/Resources/config/routing.yml"