parameters:
#    pro_gize_welcome.example.class: proGize\WelcomeBundle\Example

services:
#    pro_gize_welcome.example:
#        class: %pro_gize_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
